services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /tmp/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: es_demo
      MYSQL_ROOT_PASSWORD: root
